#!/bin/bash

set -x

rofiVersion=$(rofi -v | awk '{print $2}')

# names and values matched with ratflow config:
clFocusedActiveBorder='303030'
clFocusedActiveBackground='303030'
clFocusedActiveText='2080A0'
#clFocusedActiveText='40A0FD'
clFocusedInactiveText='303030'
fontName='FontAwesome'
fontSize=10

if [[ "$rofiVersion" < "1.3.0" ]]; then

rofi -show run -lines 8 -eh 2 -width 70 -padding 20 -opacity "90" -bw 0 -separator-style none -bc "#$clFocusedActiveBorder" -bg "#$clFocusedActiveBackground" -fg "#$clFocusedActiveText" -font "$fontName $fontSize"

else

alpha=E0
    
rofi -show run -lines 8 -eh 2 -width 70 -padding 15 -bw 0 -separator-style none -font "$fontName $fontSize" \
     -color-normal "#00$clFocusedActiveBackground, #$alpha$clFocusedActiveText, #00$clFocusedActiveBackground, #$alpha$clFocusedActiveText, #$alphaffffff" \
     -color-urgent "#$alpha$clFocusedActiveBackground, #$alphaf3843d, #$alpha$clFocusedActiveBackground, #$alpha268bd2, #$alphaffc39c" \
     -color-active "#$alpha$clFocusedActiveBackground, #$alpha$clFocusedActiveText, #$alpha$clFocusedActiveBackground, #$alpha$clFocusedActiveText, #$alpha205171" \
     -color-window "#$alpha$clFocusedActiveBackground, #$alpha$clFocusedActiveBackground, #$alpha$clFocusedActiveText"

fi
