#!/bin/bash

. common

safeCp $rfdir/app_configs/gtkrc-2.0 $HOME/.gtkrc-2.0
safeCp $rfdir/app_configs/gtk-3.0-settings.ini $HOME/.config/gtk-3.0/settings.ini
safeCp $rfdir/app_configs/qt5ct.conf $HOME/.config/qt5ct/qt5ct.conf

